#! /bin/sh

# Jazzio Labs Autotools support (modified for istatd)

# Copyright (c) 2003, 2004, 2005, 2006, 2007, 2008, 2009 Mo McRoberts.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The names of the author(s) of this software may not be used to endorse
#    or promote products derived from this software without specific prior
#    written permission.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, 
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY 
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL
# AUTHORS OF THIS SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

AUTOHEADER26=${AUTOHEADER26-autoheader}
ACLOCAL110=${ACLOCAL110-aclocal}
AUTOMAKE110=${AUTOMAKE110-automake}
AUTOCONF26=${AUTOCONF26-autoconf}

appname="$0"
srcdir="`pwd`"

fail() {
	echo "$appname: $*" >&2
	exit 1
}

oprogress() {
	echo ">>> $*"
}
progress() {
	echo " +> $*"
}

test -r "$srcdir/configure.ac" || fail "Cannot find configure.ac in $srcdir"

oprogress "Generating files in $srcdir"
progress "Generating aclocal.m4"
${ACLOCAL110} || exit

if egrep '^AC_CONFIG_HEADER' "$srcdir/configure.ac" >/dev/null ; then
	progress "Generating config.h.in"
	${AUTOHEADER26} || exit
fi
if egrep "^AM_INIT_AUTOMAKE" "$srcdir/configure.ac" >/dev/null ; then
	progress "Generating Makefile.in from Makefile.am"
	${AUTOMAKE110} --add-missing --copy || exit
fi

progress "Generating configure script"
${AUTOCONF26} || exit

